// ════════════════════════════════════════════════════════════════════════════
// Cary — Scene data for the Cary, NC city guide video
// Auto-generated by city-video-automation.py
// ════════════════════════════════════════════════════════════════════════════

import { TJBCityVideoData } from './types';

export const cary_ncData: TJBCityVideoData = {
  video_metadata: {
    title: "Cary Birth Guide: Hospitals, Doulas, Midwives & More",
    city: "Cary",
    state: "NC",
    slug: "cary-nc",
    duration_seconds: 122.50,
    fps: 30,
    medicaid: true,
    hasBirthCenter: false,
    hasAppScreenshot: true,
  },
  scenes: [
    {
      scene_id: "01_hook",
      scene_type: "tjb_city_hook",
      duration_seconds: 10.73,
      narration: "Just found out you're pregnant in Cary? Awesome. Now you've got eighty tabs open on hospitals, doulas, midwives, insurance. Let's close every single one of them right now.",
      text_content: {
        city: "Cary",
        state: "NC",
        slug: "cary-nc",
        subtitle: "Your Birth Planning Guide",
      },
      image_source: "images/cary-nc-birth-doula-skyline.webp",
    },
    {
      scene_id: "02_overview",
      scene_type: "tjb_city_bridge",
      duration_seconds: 16.40,
      narration: "Here's what we're covering in this video: which hospitals welcome doulas and midwives, the doulas and midwives you can work with in Cary, what everything costs including midwifery care, how NC Medicaid can help, and a free app that builds your birth plan step by step. Let's start with where you can deliver.",
      text_content: {
        city: "Cary",
        state: "NC",
      },
    },
    {
      scene_id: "03_hospital_1",
      scene_type: "tjb_hospital_card",
      duration_seconds: 9.93,
      narration: "Cary's top hospitals include WakeMed Cary Hospital, UNC REX Healthcare. All of them welcome doulas and have NICU support for babies who need extra care.",
      image_source: "images/cary-nc-birth-doula-skyline.webp",
      text_content: {
        name: "WakeMed Cary Hospital",
        description: "A doula-friendly hospital in Cary with NICU support and Medicaid acceptance, offering comprehensive maternity care for families.",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      },
    },
    {
      scene_id: "04_providers",
      scene_type: "tjb_provider_grid",
      duration_seconds: 8.33,
      narration: "Cary has experienced doulas and midwives ready to support you. See who's serving your area — and message them directly — in the app.",
      text_content: {
        providerCount: 12,
        screenshotPath: "images/tjb-app-dashboard.webp",
        city: "Cary",
      },
    },
    {
      scene_id: "05_app",
      scene_type: "tjb_app_feature",
      duration_seconds: 22.33,
      narration: "Here's the part every Cary mom should know about. The True Joy Birthing app is completely free — no account, no catch. Nine guided sections walk you through your entire birth plan. You can find and message doulas and midwives near you right inside the app. Then export your plan as a PDF to share with your provider. It's the tool every mom needs in her pocket.",
      text_content: {
        headline: "Build Your Birth Plan",
        screenshotPath: "images/tjb-app-dashboard.webp",
        features: [
          "Nine guided sections — hospital preferences, pain management, who's in the room",
          "Find and connect with doulas and midwives near you",
          "Export a PDF to share with your provider",
          "Free. No account needed. Works on iPhone.",
        ],
      },
    },
    {
      scene_id: "06_cost",
      scene_type: "tjb_cost_reveal",
      duration_seconds: 22.10,
      narration: "Here's the reality: a doula in Cary typically costs $1,000 to $3,000. Most doulas offer payment plans, and some accept Medicaid. Midwifery care runs $5,000 to $8,000 for home birth or birth center care, and many midwives accept insurance. The investment is real, but the support is worth every dollar.",
      text_content: {
        costRange: "$1,000–$3,000",
        label: "Doulas · $1K–$3K · Midwives · $5K–$8K",
        description: "Most doulas offer payment plans. Midwives often accept insurance.",
      },
    },
    {
      scene_id: "07_insurance",
      scene_type: "tjb_insurance_branch",
      duration_seconds: 18.57,
      narration: "NC Medicaid covers doula services for eligible enrollees. Contact your managed care plan to confirm doula reimbursement and midwife coverage details.. Even if you have private insurance, some plans now include doula benefits — it's worth a call to check. The app has resources to help you navigate your options.",
      text_content: {
        headline: "NC Medicaid Covers Doula Services",
        detail: "NC Medicaid covers doula services for eligible enrollees — contact your managed care plan to confirm reimbursement and midwife coverage details.",
        branch: "covers",
        stateName: "NC",
        policyBadge: "Medicaid",
        amount: "$1,000+",
      },
    },
    {
      scene_id: "08_cta",
      scene_type: "tjb_city_cta",
      duration_seconds: 14.10,
      narration: "A birth plan tells your care team exactly what matters to you. You can build yours with the free PDF birth plan, watch our walkthrough series, or use the mobile app. It's all free, and it's all ready for you right now. We'll put the link below.",
      text_content: {
        city: "Cary",
        slug: "cary-nc",
      },
    },
  ],
};
