// ════════════════════════════════════════════════════════════════════════════
// Huntington Beach — Scene data for the Huntington Beach, CA city guide video
// Auto-generated by city-video-automation.py
// ════════════════════════════════════════════════════════════════════════════

import { TJBCityVideoData } from './types';

export const huntington_beach_caData: TJBCityVideoData = {
  video_metadata: {
    title: "Huntington Beach Birth Guide: Hospitals, Doulas, Midwives & More",
    city: "Huntington Beach",
    state: "CA",
    slug: "huntington-beach-ca",
    duration_seconds: 153.83,
    fps: 30,
    medicaid: true,
    hasBirthCenter: true,
    hasAppScreenshot: false,
  },
  scenes: [
    {
      scene_id: "01_hook",
      scene_type: "tjb_city_hook",
      duration_seconds: 12.10,
      narration: "Just found out you're pregnant in Huntington Beach? Congratulations! Now you've got eighty tabs open on hospitals, doulas, midwives, insurance. Let's close every single one of them right now.",
      text_content: {
        city: "Huntington Beach",
        state: "CA",
        slug: "huntington-beach-ca",
        subtitle: "Your Birth Planning Guide",
      },
      image_source: "images/huntington-beach-ca-birth-doula-hero.webp",
    },
    {
      scene_id: "02_overview",
      scene_type: "tjb_city_bridge",
      duration_seconds: 20.17,
      narration: "Here's what we're covering in this video: which hospitals welcome doulas and midwives, the doulas and midwives you can work with in Huntington Beach, what everything costs including midwifery care, how CA Medicaid can help, and a free app that builds your birth plan step by step. Let's start with where you can deliver.",
      text_content: {
        city: "Huntington Beach",
        state: "CA",
      },
    },
    {
      scene_id: "03_hospital_1",
      scene_type: "tjb_hospital_card",
      duration_seconds: 9.20,
      narration: "Let's start with Hoag Hospital Newport Beach. Hoag Hospital Newport Beach is where most Huntington Beach families deliver, about 10 minutes north via PCH.",
      text_content: {
        name: "Hoag Hospital Newport Beach",
        address: "1 Hoag Dr, Newport Beach, CA 92663",
        description: "Hoag Hospital Newport Beach is where most Huntington Beach families deliver, about 10 minutes north via PCH. The Sue and Bill Gross Women's Pavilion runs the largest maternity program in Orange County with 18 private labor-delivery-recovery suites, a 49-bed postpartum unit, and a 14-bed antepartum u",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      },
      image_source: "images/hoag-hospital-newport-beach.webp",
    },
    {
      scene_id: "03_hospital_2",
      scene_type: "tjb_hospital_card",
      duration_seconds: 15.20,
      narration: "MemorialCare Saddleback Medical Center also welcomes doulas and provides NICU support. MemorialCare Saddleback Medical Center in Laguna Hills is about 20 minutes south of Huntington Beach and delivers a more intimate birth experience...",
      text_content: {
        name: "MemorialCare Saddleback Medical Center",
        address: "24452 Health Center Dr, Laguna Hills, CA 92653",
        description: "MemorialCare Saddleback Medical Center in Laguna Hills is about 20 minutes south of Huntington Beach and delivers a more intimate birth experience with private birthing suites and certified nurse midwives on staff. The Women's Hospital has delivered more than 75,000 babies and holds the CMS Birthing",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      },
      image_source: "images/saddleback-medical-center.webp",
    },
    {
      scene_id: "04_providers",
      scene_type: "tjb_provider_scroll",
      duration_seconds: 13.60,
      narration: "Huntington Beach has 4 experienced doulas and midwives ready to support you, including Madi Rose, Dee Ornelas, and Kelsey and Aurora. See who's serving your area, and message them directly, in the app.",
      text_content: {
        city: "Huntington Beach",
        providerCount: 4,
        screenshotPath: "images/huntington-beach-ca-fullpage-scroll.png",
        maxScroll: 1352,
      },
    },
    {
      scene_id: "05_app",
      scene_type: "tjb_app_feature",
      duration_seconds: 23.07,
      narration: "Here's the part every Huntington Beach mom should know about. The True Joy Birthing app is completely free — no account, no catch. Nine guided sections walk you through your entire birth plan. You can find and message doulas and midwives near you right inside the app. Then export your plan as a PDF to share with your provider. It's the tool every mom needs in her pocket.",
      text_content: {
        headline: "Build Your Birth Plan",
        features: [
          "Nine guided sections — hospital preferences, pain management, who's in the room",
          "Find and connect with doulas and midwives near you",
          "Export a PDF to share with your provider",
          "Free. No account needed. Works on iPhone.",
        ],
      },
    },
    {
      scene_id: "06_cost",
      scene_type: "tjb_cost_reveal",
      duration_seconds: 25.53,
      narration: "Here's the reality: a doula in Huntington Beach typically costs $1,200 to $3,000. Most doulas offer payment plans, and some accept Medicaid. Midwifery care runs $5,000 to $8,000 for home birth or birth center care, and many midwives accept insurance. The investment is real, but the support is worth every dollar.",
      text_content: {
        costRange: "$1,200–$3,000",
        label: "Doulas · $1K–$3K · Midwives · $5K–$8K",
        description: "Most doulas offer payment plans. Midwives often accept insurance.",
      },
    },
    {
      scene_id: "07_insurance",
      scene_type: "tjb_insurance_branch",
      duration_seconds: 20.00,
      narration: "CA Medicaid covers doula services for eligible enrollees. Contact your managed care plan to confirm doula reimbursement and midwife coverage details.. Even if you have private insurance, some plans now include doula benefits, it's worth a call to check. The app has resources to help you navigate your options.",
      text_content: {
        branch: "covers",
        stateName: "CA",
        headline: "Medicaid Covers Doulas",
        detail: "CA Medicaid covers doula services for eligible enrollees. Contact your managed care plan to confirm doula reimbursement and midwife coverage details.",
        policyBadge: "Covered",
        amount: "$1,200-$3,000",
        phoneNumber: "1-800-362-8412",
      },
    },
    {
      scene_id: "08_cta",
      scene_type: "tjb_city_cta",
      duration_seconds: 14.97,
      narration: "A birth plan tells your care team exactly what matters to you. You can build yours with the free PDF birth plan, watch our walkthrough series, or use the mobile app. It's all free, and it's all ready for you right now. We'll put the link below.",
      text_content: {
        city: "Huntington Beach",
        slug: "huntington-beach-ca",
      },
    }
  ],
};
