// ════════════════════════════════════════════════════════════════════════════
// La Habra — Scene data for the La Habra, CA city guide video
// Auto-generated by city-video-automation.py
// ════════════════════════════════════════════════════════════════════════════

import { TJBCityVideoData } from './types';

export const la_habra_caData: TJBCityVideoData = {
  video_metadata: {
    title: "La Habra Birth Guide: Hospitals, Doulas, Midwives & More",
    city: "La Habra",
    state: "California",
    slug: "la-habra-ca",
    duration_seconds: 165.03,
    fps: 30,
    medicaid: true,
    hasBirthCenter: false,
    hasAppScreenshot: false,
  },
  scenes: [
    {
      scene_id: "01_hook",
      scene_type: "tjb_city_hook",
      duration_seconds: 12.67,
      narration: "Just found out you're pregnant in La Habra? Congratulations! Now you've got eighty tabs open on hospitals, doulas, midwives, insurance. Let's close every single one of them right now.",
      text_content: {
        city: "La Habra",
        state: "California",
        slug: "la-habra-ca",
        subtitle: "Your Birth Planning Guide",
      },
      image_source: "images/la-habra-ca-birth-doula-skyline-v2.webp",
    },
    {
      scene_id: "02_overview",
      scene_type: "tjb_city_bridge",
      duration_seconds: 19.70,
      narration: "Here's what we're covering in this video: which hospitals welcome doulas and midwives, the doulas and midwives you can work with in La Habra, what everything costs including midwifery care, how California's Medi-Cal can help, and a free app that builds your birth plan step by step. Let's start with where you can deliver.",
      text_content: {
        city: "La Habra",
        state: "California",
      },
    },
    {
      scene_id: "03_hospital_1",
      scene_type: "tjb_hospital_card",
      duration_seconds: 10.00,
      narration: "Let's start with Providence St. Jude Medical Center. Providence St. Jude Medical Center in Fullerton is the closest hospital to La Habra, about 3 miles away.",
      text_content: {
        name: "Providence St. Jude Medical Center",
        address: "101 E Valencia Mesa Dr, Fullerton, CA 92835",
        description: "Providence St. Jude Medical Center in Fullerton is the closest hospital to La Habra, about 3 miles away. The facility has a 14-bed Level III NICU staffed with neonatologists and pediatric subspecialists. The maternity center offers private labor, delivery, and recovery rooms, certified nurse-midwive",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      },
      image_source: "images/la-habra-ca-hospital-providence-st-jude.webp",
    },
    {
      scene_id: "03_hospital_2",
      scene_type: "tjb_hospital_card",
      duration_seconds: 13.77,
      narration: "PIH Health Whittier Hospital also welcomes doulas and provides NICU support. PIH Health Whittier Hospital is about 10 miles from La Habra and offers a comprehensive maternity program with a Level III NICU.",
      text_content: {
        name: "PIH Health Whittier Hospital",
        address: "14555 Whittier Blvd, Whittier, CA 90602",
        description: "PIH Health Whittier Hospital is about 10 miles from La Habra and offers a comprehensive maternity program with a Level III NICU. The hospital has board-certified obstetricians, OB hospitalists, certified nurse-midwives, neonatologists, and lactation consultants on staff. Labor and delivery features ",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      },
      image_source: "images/la-habra-ca-hospital-pih-whittier.webp",
    },
    {
      scene_id: "03_hospital_3",
      scene_type: "tjb_hospital_card",
      duration_seconds: 14.10,
      narration: "Anaheim Regional Medical Center also welcomes doulas and provides NICU support. Anaheim Regional Medical Center is about 12 miles from La Habra and serves as a key maternity hospital for north Orange County.",
      text_content: {
        name: "Anaheim Regional Medical Center",
        address: "901 S Anaheim Blvd, Anaheim, CA 92805",
        description: "Anaheim Regional Medical Center is about 12 miles from La Habra and serves as a key maternity hospital for north Orange County. The facility has a Level III NICU with 11 beds, private labor and delivery suites, and 24/7 OB hospitalists and anesthesiologists. The hospital offers certified nurse-midwi",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      },
      image_source: "images/la-habra-ca-hospital-anaheim-regional.webp",
    },
    {
      scene_id: "04_providers",
      scene_type: "tjb_provider_scroll",
      duration_seconds: 15.93,
      narration: "La Habra has 3 experienced doulas and midwives ready to support you, including Aloha Lamaze and Breastfeeding Services, Temple & Terrain Doula Services, and Newborn Nurtury Doula Services. See who's serving your area, and message them directly, in the app.",
      text_content: {
        city: "La Habra",
        providerCount: 3,
        screenshotPath: "images/la-habra-ca-fullpage-scroll.png",
        maxScroll: 819,
      },
    },
    {
      scene_id: "05_app",
      scene_type: "tjb_app_feature",
      duration_seconds: 23.30,
      narration: "Here's the part every La Habra mom should know about. The True Joy Birthing app is completely free — no account, no catch. Nine guided sections walk you through your entire birth plan. You can find and message doulas and midwives near you right inside the app. Then export your plan as a PDF to share with your provider. It's the tool every mom needs in her pocket.",
      text_content: {
        headline: "Build Your Birth Plan",
        features: [
          "Nine guided sections — hospital preferences, pain management, who's in the room",
          "Find and connect with doulas and midwives near you",
          "Export a PDF to share with your provider",
          "Free. No account needed. Works on iPhone.",
        ],
      },
    },
    {
      scene_id: "06_cost",
      scene_type: "tjb_cost_reveal",
      duration_seconds: 22.73,
      narration: "Here's the reality: a doula in La Habra typically costs $800 to $2,500. Most doulas offer payment plans, and some accept Medicaid. Midwifery care runs $5,000 to $8,000 for home birth or birth center care, and many midwives accept insurance. The investment is real, but the support is worth every dollar.",
      text_content: {
        costRange: "$800–$2,500",
        label: "Doulas · $1K–$3K · Midwives · $5K–$8K",
        description: "Most doulas offer payment plans. Midwives often accept insurance.",
      },
    },
    {
      scene_id: "07_insurance",
      scene_type: "tjb_insurance_branch",
      duration_seconds: 18.33,
      narration: "California's Medi-Cal covers doula services for eligible enrollees. Contact your managed care plan to confirm doula reimbursement and midwife coverage details. Even if you have private insurance, some plans now include doula benefits, it's worth a call to check. The app has resources to help you navigate your options.",
      text_content: {
        branch: "covers",
        stateName: "California",
        headline: "Medicaid Covers Doulas",
        detail: "California's Medi-Cal covers doula services for eligible enrollees. Contact your managed care plan to confirm doula reimbursement and midwife coverage details.",
        policyBadge: "Covered",
        amount: "$800-$2,500",
        phoneNumber: "1-800-362-8412",
      },
    },
    {
      scene_id: "08_cta",
      scene_type: "tjb_city_cta",
      duration_seconds: 14.50,
      narration: "A birth plan tells your care team exactly what matters to you. You can build yours with the free PDF birth plan, watch our walkthrough series, or use the mobile app. It's all free, and it's all ready for you right now. We'll put the link below.",
      text_content: {
        city: "La Habra",
        slug: "la-habra-ca",
      },
    }
  ],
};
