// ════════════════════════════════════════════════════════════════════════════
// Newport Beach — Scene data for the Newport Beach, CA city guide video
// Auto-generated by city-video-automation.py
// ════════════════════════════════════════════════════════════════════════════

import { TJBCityVideoData } from './types';

export const newport_beach_caData: TJBCityVideoData = {
  video_metadata: {
    title: "Newport Beach Birth Guide: Hospitals, Doulas, Midwives & More",
    city: "Newport Beach",
    state: "California",
    slug: "newport-beach-ca",
    duration_seconds: 166.00,
    fps: 30,
    medicaid: true,
    hasBirthCenter: false,
    hasAppScreenshot: false,
  },
  scenes: [
    {
      scene_id: "01_hook",
      scene_type: "tjb_city_hook",
      duration_seconds: 12.00,
      narration: "Congratulations! Just found out you're pregnant in Newport Beach? Now you've got eighty tabs open on hospitals, doulas, midwives, insurance. Let's close every single one of them right now.",
      text_content: {
        city: "Newport Beach",
        state: "California",
        slug: "newport-beach-ca",
        subtitle: "Your Birth Planning Guide",
      },
      image_source: "images/newport-beach-ca-birth-doula-skyline-v2.webp",
    },
    {
      scene_id: "02_overview",
      scene_type: "tjb_city_bridge",
      duration_seconds: 18.97,
      narration: "Here's what we're covering in this video: which hospitals welcome doulas and midwives, the doulas and midwives you can work with in Newport Beach, what everything costs including midwifery care, how CA Medicaid can help, and a free app that builds your birth plan step by step. Let's start with where you can deliver.",
      text_content: {
        city: "Newport Beach",
        state: "California",
      },
    },
    {
      scene_id: "03_hospital_1",
      scene_type: "tjb_hospital_card",
      duration_seconds: 14.33,
      narration: "Let's start with Hoag Hospital Newport Beach (Sue & Bill Gross Women's Pavilion). Hoag Hospital Newport Beach's Sue & Bill Gross Women's Pavilion is one of Orange County's most comprehensive maternal and newborn care programs.",
      text_content: {
        name: "Hoag Hospital Newport Beach (Sue & Bill Gross Women's Pavilion)",
        address: "500 Newport Center Drive, Newport Beach, CA 92663",
        description: "Hoag Hospital Newport Beach's Sue & Bill Gross Women's Pavilion is one of Orange County's most comprehensive maternal and newborn care programs. The facility includes 18 private labor, delivery, and recovery suites, 49 private postpartum rooms, a 14-bed antepartum unit, and an expanded 33-bed Level ",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      },
      image_source: "images/newport-beach-ca-hospital-hoag-womens-pavilion.webp",
    },
    {
      scene_id: "03_hospital_2",
      scene_type: "tjb_hospital_card",
      duration_seconds: 14.97,
      narration: "Providence St. Joseph Hospital Orange also welcomes doulas and provides NICU support. Providence St. Joseph Hospital Orange is a full-service hospital about 10 miles from Newport Beach that delivers over 5,000 babies annually.",
      text_content: {
        name: "Providence St. Joseph Hospital Orange",
        address: "1100 W Stewart Dr, Orange, CA 92868",
        description: "Providence St. Joseph Hospital Orange is a full-service hospital about 10 miles from Newport Beach that delivers over 5,000 babies annually. The maternity center includes private labor, delivery, and recovery rooms with birthing beds and hydrotherapy options. The hospital has a Level III NICU staffe",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      },
      image_source: "images/newport-beach-ca-hospital-providence-st-joseph.webp",
    },
    {
      scene_id: "03_hospital_3",
      scene_type: "tjb_hospital_card",
      duration_seconds: 11.70,
      narration: "UC Irvine Medical Center also welcomes doulas and provides NICU support. UC Irvine Medical Center is Orange County's regional perinatal center, located about 10 miles from Newport Beach.",
      text_content: {
        name: "UC Irvine Medical Center",
        address: "1 Orange Grove Drive, Orange, CA 92868",
        description: "UC Irvine Medical Center is Orange County's regional perinatal center, located about 10 miles from Newport Beach. As a major academic medical center, it offers comprehensive maternity care including private labor and delivery suites, a 36-bed Level III NICU, and maternal-fetal medicine specialists f",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      },
      image_source: "images/newport-beach-ca-hospital-uci-medical-center.webp",
    },
    {
      scene_id: "04_providers",
      scene_type: "tjb_provider_scroll",
      duration_seconds: 12.00,
      narration: "Newport Beach has 3 experienced doulas and midwives ready to support you, including Madi Rose Doula, Ashley McIntosh, and Diana Roth. See who's serving your area, and message them directly, in the app.",
      text_content: {
        city: "Newport Beach",
        providerCount: 3,
        screenshotPath: "images/newport-beach-ca-fullpage-scroll.png",
        maxScroll: 968,
      },
    },
    {
      scene_id: "05_app",
      scene_type: "tjb_app_feature",
      duration_seconds: 23.60,
      narration: "Here's the part every Newport Beach mom should know about. The True Joy Birthing app is completely free — no account, no catch. Nine guided sections walk you through your entire birth plan. You can find and message doulas and midwives near you right inside the app. Then export your plan as a PDF to share with your provider. It's the tool every mom needs in her pocket.",
      text_content: {
        headline: "Build Your Birth Plan",
        features: [
          "Nine guided sections — hospital preferences, pain management, who's in the room",
          "Find and connect with doulas and midwives near you",
          "Export a PDF to share with your provider",
          "Free. No account needed. Works on iPhone.",
        ],
      },
    },
    {
      scene_id: "06_cost",
      scene_type: "tjb_cost_reveal",
      duration_seconds: 22.10,
      narration: "Here's the reality: a doula in Newport Beach typically costs $800 to $2,500. Most doulas offer payment plans, and some accept Medicaid. Midwifery care runs $5,000 to $8,000 for home birth or birth center care, and many midwives accept insurance. The investment is real, but the support is worth every dollar.",
      text_content: {
        costRange: "$800–$2,500",
        label: "Doulas · $1K–$3K · Midwives · $5K–$8K",
        description: "Most doulas offer payment plans. Midwives often accept insurance.",
      },
    },
    {
      scene_id: "07_insurance",
      scene_type: "tjb_insurance_branch",
      duration_seconds: 20.40,
      narration: "CA Medicaid covers doula services for eligible enrollees. Contact your managed care plan to confirm doula reimbursement and midwife coverage details.. Even if you have private insurance, some plans now include doula benefits, it's worth a call to check. The app has resources to help you navigate your options.",
      text_content: {
        branch: "covers",
        stateName: "California",
        headline: "Medicaid Covers Doulas",
        detail: "CA Medicaid covers doula services for eligible enrollees. Contact your managed care plan to confirm doula reimbursement and midwife coverage details.",
        policyBadge: "Covered",
        amount: "$800-$2,500",
        phoneNumber: "1-800-362-8412",
      },
    },
    {
      scene_id: "08_cta",
      scene_type: "tjb_city_cta",
      duration_seconds: 15.93,
      narration: "A birth plan tells your care team exactly what matters to you. You can build yours with the free PDF birth plan, watch our walkthrough series, or use the mobile app. It's all free, and it's all ready for you right now. We'll put the link below.",
      text_content: {
        city: "Newport Beach",
        slug: "newport-beach-ca",
      },
    }
  ],
};
