// ════════════════════════════════════════════════════════════════════════════
// Rancho Cucamonga — Scene data for the Rancho Cucamonga, CA city guide video
// Auto-generated by city-video-automation.py
// ════════════════════════════════════════════════════════════════════════════

import { TJBCityVideoData } from './types';

export const rancho_cucamonga_caData: TJBCityVideoData = {
  video_metadata: {
    title: "Rancho Cucamonga Birth Guide: Hospitals, Doulas, Midwives & More",
    city: "Rancho Cucamonga",
    state: "CA",
    slug: "rancho-cucamonga-ca",
    duration_seconds: 155.50,
    fps: 30,
    medicaid: true,
    hasBirthCenter: true,
    hasAppScreenshot: false,
  },
  scenes: [
    {
      scene_id: "01_hook",
      scene_type: "tjb_city_hook",
      duration_seconds: 12.80,
      narration: "Just found out you're pregnant in Rancho Cucamonga? Congratulations! Now you've got eighty tabs open on hospitals, doulas, midwives, insurance. Let's close every single one of them right now.",
      text_content: {
        city: "Rancho Cucamonga",
        state: "CA",
        slug: "rancho-cucamonga-ca",
        subtitle: "Your Birth Planning Guide",
      },
      image_source: "images/rancho-cucamonga-ca-birth-doula-hero.webp",
    },
    {
      scene_id: "02_overview",
      scene_type: "tjb_city_bridge",
      duration_seconds: 17.37,
      narration: "Here's what we're covering in this video: which hospitals welcome doulas and midwives, the doulas and midwives you can work with in Rancho Cucamonga, what everything costs including midwifery care, how CA Medicaid can help, and a free app that builds your birth plan step by step. Let's start with where you can deliver.",
      text_content: {
        city: "Rancho Cucamonga",
        state: "CA",
      },
    },
    {
      scene_id: "03_hospital_1",
      scene_type: "tjb_hospital_card",
      duration_seconds: 14.67,
      narration: "Let's start with San Antonio Regional Hospital. San Antonio Regional Hospital in nearby Upland, about 5 miles from Rancho Cucamonga, is a 363-bed nonprofit hospital whose Family Birth Center was named a U.S.",
      text_content: {
        name: "San Antonio Regional Hospital",
        address: "999 San Bernardino Rd, Upland, CA 91786",
        description: "San Antonio Regional Hospital in nearby Upland, about 5 miles from Rancho Cucamonga, is a 363-bed nonprofit hospital whose Family Birth Center was named a U.S. News Best Hospital for Maternity Care and is a designated Baby-Friendly hospital. Labor and delivery happens in private birthing suites with",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      },
      image_source: "images/san-antonio-regional-hospital.webp",
    },
    {
      scene_id: "03_hospital_2",
      scene_type: "tjb_hospital_card",
      duration_seconds: 16.67,
      narration: "Arrowhead Regional Medical Center also welcomes doulas and provides NICU support. Arrowhead Regional Medical Center in Colton, about 15 miles southeast of Rancho Cucamonga, is San Bernardino County's public hospital and a...",
      text_content: {
        name: "Arrowhead Regional Medical Center",
        address: "400 N Pepper Ave, Colton, CA 92324",
        description: "Arrowhead Regional Medical Center in Colton, about 15 miles southeast of Rancho Cucamonga, is San Bernardino County's public hospital and a Baby-Friendly designated facility with a state-of-the-art Level III Neonatal Intensive Care Unit where premature or critically-ill newborns get advanced care bu",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      },
      image_source: "images/arrowhead-regional-medical-center.webp",
    },
    {
      scene_id: "04_providers",
      scene_type: "tjb_provider_scroll",
      duration_seconds: 13.30,
      narration: "Rancho Cucamonga has 4 experienced doulas and midwives ready to support you, including Selina Pasillas, Annie Griffith, and Nicole Jones. See who's serving your area, and message them directly, in the app.",
      text_content: {
        city: "Rancho Cucamonga",
        providerCount: 4,
        screenshotPath: "images/rancho-cucamonga-ca-fullpage-scroll.png",
        maxScroll: 1362,
      },
    },
    {
      scene_id: "05_app",
      scene_type: "tjb_app_feature",
      duration_seconds: 25.53,
      narration: "Here's the part every Rancho Cucamonga mom should know about. The True Joy Birthing app is completely free — no account, no catch. Nine guided sections walk you through your entire birth plan. You can find and message doulas and midwives near you right inside the app. Then export your plan as a PDF to share with your provider. It's the tool every mom needs in her pocket.",
      text_content: {
        headline: "Build Your Birth Plan",
        features: [
          "Nine guided sections — hospital preferences, pain management, who's in the room",
          "Find and connect with doulas and midwives near you",
          "Export a PDF to share with your provider",
          "Free. No account needed. Works on iPhone.",
        ],
      },
    },
    {
      scene_id: "06_cost",
      scene_type: "tjb_cost_reveal",
      duration_seconds: 22.90,
      narration: "Here's the reality: a doula in Rancho Cucamonga typically costs $1,000 to $2,500. Most doulas offer payment plans, and some accept Medicaid. Midwifery care runs $5,000 to $8,000 for home birth or birth center care, and many midwives accept insurance. The investment is real, but the support is worth every dollar.",
      text_content: {
        costRange: "$1,000–$2,500",
        label: "Doulas · $1K–$3K · Midwives · $5K–$8K",
        description: "Most doulas offer payment plans. Midwives often accept insurance.",
      },
    },
    {
      scene_id: "07_insurance",
      scene_type: "tjb_insurance_branch",
      duration_seconds: 17.13,
      narration: "CA Medicaid covers doula services for eligible enrollees. Contact your managed care plan to confirm doula reimbursement and midwife coverage details.. Even if you have private insurance, some plans now include doula benefits, it's worth a call to check. The app has resources to help you navigate your options.",
      text_content: {
        branch: "covers",
        stateName: "CA",
        headline: "Medicaid Covers Doulas",
        detail: "CA Medicaid covers doula services for eligible enrollees. Contact your managed care plan to confirm doula reimbursement and midwife coverage details.",
        policyBadge: "Covered",
        amount: "$1,000-$2,500",
        phoneNumber: "1-800-362-8412",
      },
    },
    {
      scene_id: "08_cta",
      scene_type: "tjb_city_cta",
      duration_seconds: 15.13,
      narration: "A birth plan tells your care team exactly what matters to you. You can build yours with the free PDF birth plan, watch our walkthrough series, or use the mobile app. It's all free, and it's all ready for you right now. We'll put the link below.",
      text_content: {
        city: "Rancho Cucamonga",
        slug: "rancho-cucamonga-ca",
      },
    }
  ],
};
