// ════════════════════════════════════════════════════════════════════════════
// Redwood City — Scene data for the Redwood City, CA city guide video
// Auto-generated by city-video-automation.py
// ════════════════════════════════════════════════════════════════════════════

import { TJBCityVideoData } from './types';

export const redwood_city_caData: TJBCityVideoData = {
  video_metadata: {
    title: "Redwood City Birth Guide: Hospitals, Doulas, Midwives & More",
    city: "Redwood City",
    state: "California",
    slug: "redwood-city-ca",
    duration_seconds: 148.33,
    fps: 30,
    medicaid: true,
    hasBirthCenter: false,
    hasAppScreenshot: false,
  },
  scenes: [
    {
      scene_id: "01_hook",
      scene_type: "tjb_city_hook",
      duration_seconds: 12.67,
      narration: "Just found out you're pregnant in Redwood City? Congratulations! Now you've got eighty tabs open on hospitals, doulas, midwives, insurance. Let's close every single one of them right now.",
      text_content: {
        city: "Redwood City",
        state: "California",
        slug: "redwood-city-ca",
        subtitle: "Your Birth Planning Guide",
      },
      image_source: "images/redwood-city-ca-birth-doula-skyline-v2.webp",
    },
    {
      scene_id: "02_overview",
      scene_type: "tjb_city_bridge",
      duration_seconds: 17.20,
      narration: "Here's what we're covering in this video: which hospitals welcome doulas and midwives, the doulas and midwives you can work with in Redwood City, what everything costs including midwifery care, how CA Medicaid can help, and a free app that builds your birth plan step by step. Let's start with where you can deliver.",
      text_content: {
        city: "Redwood City",
        state: "California",
      },
    },
    {
      scene_id: "03_hospital_1",
      scene_type: "tjb_hospital_card",
      duration_seconds: 10.57,
      narration: "Let's start with Sequoia Hospital. Sequoia Hospital in Redwood City is a nationally recognized maternity center featuring a Family Birth Center with private LDR rooms.",
      image_source: "images/redwood-city-ca-hospital-sequoia.webp",
      text_content: {
        name: "Sequoia Hospital",
        address: "170 Alameda de las Pulgas, Redwood City, CA 94062",
        description: "Sequoia Hospital in Redwood City is a nationally recognized maternity center featuring a Family Birth Center with private LDR rooms. The hospital has a Level II NICU staffed by Lucile Packard Children's Hospital Stanford neonatologists, certified nurse-midwives on staff, and 24/7 OB hospitalists. Se",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      },

    },
    {
      scene_id: "03_hospital_2",
      scene_type: "tjb_hospital_card",
      duration_seconds: 14.00,
      narration: "Kaiser Permanente Redwood City Medical Center also welcomes doulas and provides NICU support. Kaiser Permanente Redwood City Medical Center offers labor and delivery services with a Level II nursery for newborns needing extra care.",
      image_source: "images/redwood-city-ca-hospital-kp.webp",
      text_content: {
        name: "Kaiser Permanente Redwood City Medical Center",
        address: "1100 Veterans Blvd, Redwood City, CA 94063",
        description: "Kaiser Permanente Redwood City Medical Center offers labor and delivery services with a Level II nursery for newborns needing extra care. The hospital features private birthing suites, 24/7 anesthesia coverage, and certified nurse-midwives on staff. Doulas are welcome as support persons. The hospita",
        badges: ["Doula-Friendly", "NICU", "Medicaid"],
      },

    },
    {
      scene_id: "04_providers",
      scene_type: "tjb_provider_scroll",
      duration_seconds: 13.47,
      narration: "Redwood City has 3 experienced doulas and midwives ready to support you, including Together Birth & Body, Mairi Doula, and Redwood Doulas. See who's serving your area, and message them directly, in the app.",
      text_content: {
        city: "Redwood City",
        providerCount: 3,
        screenshotPath: "images/redwood-city-ca-fullpage-scroll.png",
        maxScroll: 600,
      },
    },
    {
      scene_id: "05_app",
      scene_type: "tjb_app_feature",
      duration_seconds: 21.37,
      narration: "Here's the part every Redwood City mom should know about. The True Joy Birthing app is completely free — no account, no catch. Nine guided sections walk you through your entire birth plan. You can find and message doulas and midwives near you right inside the app. Then export your plan as a PDF to share with your provider. It's the tool every mom needs in her pocket.",
      text_content: {
        headline: "Build Your Birth Plan",
        features: [
          "Nine guided sections — hospital preferences, pain management, who's in the room",
          "Find and connect with doulas and midwives near you",
          "Export a PDF to share with your provider",
          "Free. No account needed. Works on iPhone.",
        ],
      },
    },
    {
      scene_id: "06_cost",
      scene_type: "tjb_cost_reveal",
      duration_seconds: 22.57,
      narration: "Here's the reality: a doula in Redwood City typically costs $800 to $2,500. Most doulas offer payment plans, and some accept Medicaid. Midwifery care runs $5,000 to $8,000 for home birth or birth center care, and many midwives accept insurance. The investment is real, but the support is worth every dollar.",
      text_content: {
        costRange: "$800–$2,500",
        label: "Doulas · $1K–$3K · Midwives · $5K–$8K",
        description: "Most doulas offer payment plans. Midwives often accept insurance.",
      },
    },
    {
      scene_id: "07_insurance",
      scene_type: "tjb_insurance_branch",
      duration_seconds: 20.97,
      narration: "CA Medicaid covers doula services for eligible enrollees. Contact your managed care plan to confirm doula reimbursement and midwife coverage details.. Even if you have private insurance, some plans now include doula benefits, it's worth a call to check. The app has resources to help you navigate your options.",
      text_content: {
        branch: "covers",
        stateName: "California",
        headline: "Medicaid Covers Doulas",
        detail: "CA Medicaid covers doula services for eligible enrollees. Contact your managed care plan to confirm doula reimbursement and midwife coverage details.",
        policyBadge: "Covered",
        amount: "$800-$2,500",
        phoneNumber: "1-800-362-8412",
      },
    },
    {
      scene_id: "08_cta",
      scene_type: "tjb_city_cta",
      duration_seconds: 15.53,
      narration: "A birth plan tells your care team exactly what matters to you. You can build yours with the free PDF birth plan, watch our walkthrough series, or use the mobile app. It's all free, and it's all ready for you right now. We'll put the link below.",
      text_content: {
        city: "Redwood City",
        slug: "redwood-city-ca",
      },
    }
  ],
};
