// ════════════════════════════════════════════════════════════════════════════
// San Mateo — Scene data for the San Mateo, California city guide video
// Auto-generated by city-video-automation.py (video_outreach stage)
// ════════════════════════════════════════════════════════════════════════════

import { TJBCityVideoData } from './types';

export const san_mateo_caData: TJBCityVideoData = {
  video_metadata: {
    title: "San Mateo Birth Guide: Hospitals, Doulas, Midwives & More",
    city: "San Mateo",
    state: "California",
    slug: "san-mateo-ca",
    duration_seconds: 195.07,
    fps: 30,
    medicaid: true,
    hasBirthCenter: false,
    hasAppScreenshot: false,
  },
  scenes: [
    {
      scene_id: "01_hook",
      scene_type: "tjb_city_hook",
      duration_seconds: 13.60,
      narration: "Just found out you're pregnant in San Mateo? Congratulations! Now you've got eighty tabs open on hospitals, doulas, midwives, insurance. Let's close every single one of them right now.",
      text_content: {
        city: "San Mateo",
        state: "California",
        slug: "san-mateo-ca",
        subtitle: "Your Birth Planning Guide",
      },
      image_source: "images/san-mateo-ca-birth-doula-skyline-v2.webp",
    },
    {
      scene_id: "02_overview",
      scene_type: "tjb_city_bridge",
      duration_seconds: 19.83,
      narration: "Here's what we're covering in this video: which hospitals welcome doulas and midwives, the doulas and midwives you can work with in San Mateo, what everything costs including midwifery care, how California's Medi-Cal can help, and a free app that builds your birth plan step by step. Let's start with where you can deliver.",
      text_content: {
        city: "San Mateo",
        state: "California",
      },
    },
    {
      scene_id: "03_hospital_1",
      scene_type: "tjb_hospital_card",
      duration_seconds: 28.57,
      narration: "Let's start with San Mateo Medical Center, the county's public hospital, located right in the city of San Mateo. The facility offers full-service labor and delivery with private birthing suites, 24/7 OB hospitalists, and certified nurse-midwives on staff. It provides comprehensive maternity care including prenatal, delivery, and postpartum services, and it accepts Medi-Cal and most major insurance plans, with language interpretation services available.",
      text_content: {
        name: "San Mateo Medical Center",
        address: "222 W 39th Ave, San Mateo, CA 94403",
        description: "San Mateo Medical Center is San Mateo County's public hospital with full-service labor and delivery, private birthing suites, 24/7 OB hospitalists, and certified nurse-midwives on staff. Accepts Medi-Cal and most major insurance plans. Doulas are welcome as support persons.",
        badges: ["Doula-Friendly", "Medi-Cal Accepted", "Public Hospital"],
      },
      image_source: "images/san-mateo-ca-hospital-smc.webp",
    },
    {
      scene_id: "03_hospital_2",
      scene_type: "tjb_hospital_card",
      duration_seconds: 26.63,
      narration: "Sequoia Hospital in Redwood City is about ten miles from San Mateo and offers a Family Birth Center with private LDR rooms. It has a Level II NICU staffed by Stanford Children's neonatologists, certified nurse-midwives on staff, and 24/7 OB hospitalists. It's a Blue Shield of California Blue Distinction Center for maternity care, and it follows a family-centered care model with couplet care so mother and baby remain together.",
      text_content: {
        name: "Sequoia Hospital",
        address: "170 Alameda de las Pulgas, Redwood City, CA 94062",
        description: "Sequoia Hospital in Redwood City is about 10 miles from San Mateo with a Family Birth Center featuring private LDR rooms, a Level II NICU staffed by Stanford Children's neonatologists, certified nurse-midwives, and 24/7 OB hospitalists. Blue Distinction Center for maternity care with a family-centered couplet care model.",
        badges: ["Doula-Friendly", "Level II NICU", "CNM Midwives", "Medi-Cal"],
      },
      image_source: "images/san-mateo-ca-hospital-sequoia.webp",
    },
    {
      scene_id: "04_providers",
      scene_type: "tjb_provider_scroll",
      duration_seconds: 13.43,
      narration: "San Mateo has experienced doulas and midwives ready to support you, including San Mateo Doula, Thais Mendonca Schweitzer, and Sweetbay Doula. See who's serving your area, and message them directly, in the app.",
      text_content: {
        city: "San Mateo",
        providerCount: 3,
        screenshotPath: "images/san-mateo-ca-fullpage-scroll.png",
        maxScroll: 847,
      },
    },
    {
      scene_id: "05_app",
      scene_type: "tjb_app_feature",
      duration_seconds: 25.27,
      narration: "Here's the part every San Mateo mom should know about. The True Joy Birthing app is completely free — no account, no catch. Nine guided sections walk you through your entire birth plan. You can find and message doulas and midwives near you right inside the app. Then export your plan as a PDF to share with your provider. It's the tool every mom needs in her pocket.",
      text_content: {
        headline: "Build Your Birth Plan",
        features: [
          "Nine guided sections — hospital preferences, pain management, who's in the room",
          "Find and connect with doulas and midwives near you",
          "Export a PDF to share with your provider",
          "Free. No account needed. Works on iPhone.",
        ],
      },
    },
    {
      scene_id: "06_cost",
      scene_type: "tjb_cost_reveal",
      duration_seconds: 24.47,
      narration: "Here's the reality: a doula in San Mateo typically costs $800 to $2,500. Most doulas offer payment plans, and because California's Medi-Cal covers doula services, more families here can get support. Midwifery care runs roughly $5,000 to $8,000 for out-of-hospital care, and many midwives accept insurance. The investment is real, but the support is worth every dollar.",
      text_content: {
        costRange: "$800–$2,500",
        label: "Doulas · $800–$2,500 · Midwives · $5K–$8K",
        description: "Most doulas offer payment plans. Midwives often accept insurance.",
      },
    },
    {
      scene_id: "07_insurance",
      scene_type: "tjb_insurance_branch",
      duration_seconds: 28.80,
      narration: "And here's the good news: California's Medi-Cal program has covered full-spectrum doula services as a preventive benefit since January 1, 2023, including prenatal and postpartum visits and support for labor and delivery. Enrolled doulas bill Medi-Cal through the state health department. Just confirm your doula is a Medi-Cal enrolled provider before your first visit. Even with private insurance, some plans now include doula benefits — it's worth a call to check.",
      text_content: {
        branch: "covers",
        stateName: "California",
        headline: "Medi-Cal Covers Doulas",
        detail: "California's Medi-Cal has covered full-spectrum doula services as a preventive benefit since January 1, 2023. Enrolled doulas bill Medi-Cal through the Department of Health Care Services. Confirm your doula is a Medi-Cal enrolled provider before your first visit.",
        policyBadge: "Covered",
        amount: "$800-$2,500",
        phoneNumber: "1-800-362-8412",
      },
    },
    {
      scene_id: "08_cta",
      scene_type: "tjb_city_cta",
      duration_seconds: 14.47,
      narration: "A birth plan tells your care team exactly what matters to you. You can build yours with the free PDF birth plan, watch our walkthrough series, or use the mobile app. It's all free, and it's all ready for you right now. We'll put the link below.",
      text_content: {
        city: "San Mateo",
        slug: "san-mateo-ca",
      },
    },
  ],
};
